#!/bin/bash
# Script to copy all of my rc files into my WorkDocs directory for version control

RC_FILE_LIST=".bash_profile .bashrc .gitconfig .inputrc .profile .vimrc .zlogin .zshrc"

cd $HOME/WorkDocs/rcfiles

for rcfile in $RC_FILE_LIST ; do
  cp $HOME/$rcfile ./
done
