#!/usr/bin/env ruby
# code: language=ruby

require_relative "lib/servers"

def usage!
  puts <<~usage
  Usage: uninstall-servers [<server>...]
  usage

  exit 1
end

usage! if ARGV.empty?

Servers::Registry.servers_for_args(ARGV).each(&:uninstall)
